# Generated by Django 2.2.6 on 2019-11-07 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Date_of_birth', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('approve', models.BooleanField(blank=True, default=False)),
                ('Father_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=1000)),
                ('files', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('update', models.CharField(blank=True, max_length=100)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=1000)),
                ('files', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='child_stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('files', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Class')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Class'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Dropped_or_pickup', models.BooleanField(blank=True, default=False)),
                ('drop_time', models.DateTimeField(auto_now_add=True)),
                ('pick_up_time', models.DateTimeField(auto_now=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Class')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
