# Generated by Django 2.2.6 on 2019-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20191108_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='type_of_application',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Holiday', 'Holiday')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
