# Generated by Django 2.2.6 on 2019-11-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_leaves_fromto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='fromto',
        ),
    ]
